# Generated by Django 5.1.7 on 2025-04-01 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('drive', models.CharField(max_length=10)),
                ('usage_percent', models.FloatField()),
                ('total_space', models.BigIntegerField()),
                ('used_space', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
