# Generated by Django 5.1.7 on 2025-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('change_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
