# Generated by Django 5.1.7 on 2025-04-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_filechange_delete_filechangelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filechange',
            options={'ordering': ['-timestamp'], 'verbose_name': 'File Change Log', 'verbose_name_plural': 'File Change Logs'},
        ),
    ]
